#!/bin/sh
# gen-trust-anchors.sh - regenerate src/impl/x86_64/tls/trust_anchors.c from the
# system CA bundle using BearSSL's brssl tool. Run inside the build image:
#   docker run --rm -v "${PWD}:/root/env" myos-buildenv sh scripts/gen-trust-anchors.sh
set -e

BUNDLE=${1:-/etc/ssl/certs/ca-certificates.crt}
OUT=src/impl/x86_64/tls/trust_anchors.c
TOOL=/tmp/bearssl-host

rm -rf "$TOOL"
cp -r "${BEARSSL_DIR:-/root/bearssl}" "$TOOL"
make -C "$TOOL" CC=gcc BUILD=hostbuild >/dev/null

{
    echo "/* Generated by scripts/gen-trust-anchors.sh from $(basename "$BUNDLE"). Do not edit. */"
    echo "#include <stddef.h>"
    echo "#include <bearssl.h>"
    echo
    "$TOOL/hostbuild/brssl" ta -q "$BUNDLE"
    echo
    echo "const br_x509_trust_anchor *const tls_trust_anchors = TAs;"
    echo "const size_t tls_trust_anchors_num = TAs_NUM;"
} > "$OUT"

echo "wrote $OUT ($(grep -c 'BR_X509_TA_CA' "$OUT") trust anchors)"
