#!/usr/bin/env python3
"""Convert a PSF2 console font with a Unicode table (e.g. Debian's
Uni2-Terminus16.psf.gz from console-setup-linux) into a 256-glyph, code page
437 indexed 8x16 bitmap for the framebuffer console.

    python3 scripts/gen-font.py Uni2-Terminus16.psf.gz > src/impl/x86_64/lib/font8x16.c
"""
import gzip
import struct
import sys

# Code page 437 (the VGA text-mode character set) -> Unicode code point.
CP437_HIGH = (
    "ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»"
    "░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀"
    "αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ "
)
CP437_LOW = "\u0000☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼"


def cp437_to_unicode(i):
    if i < 32:
        return ord(CP437_LOW[i])
    if i < 127:
        return i
    if i == 127:
        return ord("⌂")
    return ord(CP437_HIGH[i - 128])


def load_psf1(data):
    mode, size = data[2], data[3]
    if size != 16:
        sys.exit(f"need an 8x16 font, got 8x{size}")
    count = 512 if mode & 1 else 256
    glyphs = [data[4 + i * 16: 4 + (i + 1) * 16] for i in range(count)]
    umap = {}
    if mode & 2:  # Unicode table: uint16 code points per glyph, 0xFFFF terminated
        pos = 4 + count * 16
        for g in range(count):
            in_seq = False
            while True:
                (u,) = struct.unpack_from("<H", data, pos)
                pos += 2
                if u == 0xFFFF:
                    break
                if u == 0xFFFE:
                    in_seq = True
                elif not in_seq:
                    umap.setdefault(u, g)
    return glyphs, umap


def load_psf2(path):
    data = gzip.open(path).read() if path.endswith(".gz") else open(path, "rb").read()
    if data[:2] == b"\x36\x04":
        return load_psf1(data)
    magic, _ver, hdr, flags, count, size, height, width = struct.unpack_from("<8I", data, 0)
    if magic != 0x864AB572:
        sys.exit("not a PSF2 font")
    if (width, height) != (8, 16) or size != 16:
        sys.exit(f"need an 8x16 font, got {width}x{height}")
    glyphs = [data[hdr + i * size: hdr + (i + 1) * size] for i in range(count)]

    umap = {}
    if flags & 1:  # Unicode table: UTF-8 sequences per glyph, 0xFF terminated
        pos = hdr + count * size
        for g in range(count):
            end = data.index(b"\xff", pos)
            entry = data[pos:end]
            pos = end + 1
            for part in entry.split(b"\xfe")[:1]:  # skip combining sequences
                for ch in part.decode("utf-8", "ignore"):
                    umap.setdefault(ord(ch), g)
    return glyphs, umap


def main():
    glyphs, umap = load_psf2(sys.argv[1])
    blank = bytes(16)
    out, missing = [], []
    for i in range(256):
        g = umap.get(cp437_to_unicode(i))
        if g is None and i < 128:
            g = umap.get(i)
        if g is None:
            missing.append(i)
        out.append(glyphs[g] if g is not None else blank)

    print("/* Generated by scripts/gen-font.py from %s. Do not edit." % sys.argv[1].split("/")[-1])
    print(" * Terminus Font, Copyright (c) Dimitar Toshkov Zhekov,")
    print(" * licensed under the SIL Open Font License 1.1. Indexed by code page 437. */")
    print("#include <stdint.h>\n")
    print("const uint8_t font8x16[256][16] = {")
    for i, g in enumerate(out):
        print("    {" + ", ".join("0x%02x" % b for b in g) + "},  /* %d */" % i)
    print("};")
    if missing:
        print("/* no glyph for CP437 codes: %s */" % ", ".join(map(str, missing)))


if __name__ == "__main__":
    main()
